### ISSUE TITLE
Run/Pause button out of sincronicity with emulator state.

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#35] opened 2024-09-10 17:35 UTC
When the emulator is running, the Run/Pause button must be in Pause mode (you press to pause).
When the emulator is paused, the button must be in Run mode (you press to run).
![Screenshot at 2024-09-10 14-34-49](https://github.com/user-attachments/assets/77aaa9e6-91cc-49d6-b76a-6100cbacbb40)
Here the emulator is paused, but the button is still in Pause mode, not Run mode. You need to press the button twice in order to continue execution.

**Comment by Zeal8bit** [comment] 2024-09-11 01:02
Hello @Candid-Moe,

How did you enter this state? How to reproduce this issue? On my side when the target is stopped because of a breakpoint, the icon is correct, it shows `Continue`

**Comment by Candid-Moe** [comment] 2024-09-11 17:40
I see that now we are back to two buttons again, so this issue is now outdated.

**Comment by Zeal8bit** [comment] 2024-09-12 00:25
@Candid-Moe We didn't go back to two buttons again, it was due to a conflict after merging a PR. I re-open this issue, and have to try to see if your issue is fixed now.

**Comment by Zeal8bit** [comment] 2024-10-17 04:24
This should be fixed now, closing

**Closed by Zeal8bit** 2024-10-17 04:24 UTC
